import type {
  ParsedWsdl,
  ParsedType,
  ParsedEnum,
  ParsedField,
} from "../parser/wsdl-parser.js";

function indent(level: number): string {
  return "  ".repeat(level);
}

function fieldToString(field: ParsedField, indentLevel: number): string {
  const lines: string[] = [];
  if (field.precisionRisk) {
    lines.push(
      `${indent(indentLevel)}/** WARNING: values > Number.MAX_SAFE_INTEGER lose precision */`,
    );
  }
  const optional = field.isOptional ? "?" : "";
  const arraySuffix = field.isArray ? "[]" : "";
  lines.push(
    `${indent(indentLevel)}${field.name}${optional}: ${field.tsType}${arraySuffix};`,
  );
  return lines.join("\n");
}

function emitInterface(type: ParsedType): string {
  const lines: string[] = [];
  lines.push(`export interface ${type.name} {`);
  for (const field of type.fields) {
    lines.push(fieldToString(field, 1));
  }
  lines.push("}");
  return lines.join("\n");
}

function escapeStringLiteral(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function emitEnum(enumType: ParsedEnum): string {
  const values = enumType.values
    .map((v) => `"${escapeStringLiteral(v)}"`)
    .join(" | ");
  return `export type ${enumType.name} = ${values};`;
}

function emitServiceDefinition(parsed: ParsedWsdl): string {
  const lines: string[] = [];
  const defName = parsed.services.length === 1
    ? `${parsed.services[0].name}Definition`
    : "GeneratedServiceDefinition";

  lines.push(`export interface ${defName} extends ServiceDefinition {`);

  for (const service of parsed.services) {
    lines.push(`${indent(1)}${service.name}: {`);
    for (const port of service.ports) {
      lines.push(`${indent(2)}${port.name}: {`);
      for (const op of port.operations) {
        lines.push(`${indent(3)}${op.name}: {`);
        lines.push(`${indent(4)}input: ${op.input.name};`);
        lines.push(`${indent(4)}output: ${op.output.name};`);
        lines.push(`${indent(3)}};`);
      }
      lines.push(`${indent(2)}};`);
    }
    lines.push(`${indent(1)}};`);
  }

  lines.push("}");
  return lines.join("\n");
}

function emitFactoryFunction(parsed: ParsedWsdl): string {
  const defName = parsed.services.length === 1
    ? `${parsed.services[0].name}Definition`
    : "GeneratedServiceDefinition";

  const clientType =
    parsed.services.length === 1
      ? `${parsed.services[0].name}Client`
      : "GeneratedClient";

  const factoryName =
    parsed.services.length === 1
      ? `create${parsed.services[0].name}Client`
      : "createGeneratedClient";

  const lines: string[] = [];

  lines.push(`export type ${clientType} = InferClient<${defName}>;`);
  lines.push("");
  lines.push(
    `export async function ${factoryName}(wsdlUrl: string, options?: SoapClientOptions): Promise<${clientType}> {`,
  );
  lines.push(
    `${indent(1)}return createSoapClient<${defName}>(wsdlUrl, options);`,
  );
  lines.push("}");

  return lines.join("\n");
}

/**
 * Generates a complete TypeScript source file from a parsed WSDL.
 */
export function generateTypeScript(parsed: ParsedWsdl, sourceWsdl: string): string {
  const emittedTypes = new Set<string>();
  const sections: string[] = [];

  sections.push(
    `// Auto-generated by tsoap-cli — do not edit`,
    `// Source: ${sourceWsdl}`,
    `// Generated: ${new Date().toISOString()}`,
    "",
    `import { createSoapClient } from "typed-soap";`,
    `import type { ServiceDefinition, InferClient, SoapClientOptions } from "typed-soap";`,
    "",
  );

  for (const enumType of parsed.enums) {
    sections.push(emitEnum(enumType));
    sections.push("");
  }

  for (const type of parsed.types) {
    if (!emittedTypes.has(type.name)) {
      sections.push(emitInterface(type));
      sections.push("");
      emittedTypes.add(type.name);
    }
  }

  sections.push(emitServiceDefinition(parsed));
  sections.push("");
  sections.push(emitFactoryFunction(parsed));
  sections.push("");

  return sections.join("\n");
}
